version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3050:80"
    restart: always
